### ISSUE TITLE
Prefer  ElSql#getSql(String, Map<String, ?>) over ElSql#getSql(String, Map<String, Object>)

### ISSUE THREAD

**Issue by zimmi** [OpenGamma/ElSql#13]
Essentially, this is my code:

```java
ElSql elSql = ElSql.parse(ElSqlConfig.DEFAULT, Main.class.getResource("/sql/queries.elsql"));
Map<String, String> params = Collections.singletonMap("key", "value");
String sql = elSql.getSql("SomeQuery", params);
```

That won't compile, since ElSql#getSql explicitly takes a Map\<String, Object>.
In this case making it
```java
Map<String, Object> params = Collections.singletonMap("key", "value");
```
would be an obvious fix, but that Map might come from somewhere else and casting is somewhat ugly.

Changing the signature of ElSql#getSql to take a Map\<String, ?> instead would fix this minor issue in a backward compatible way, or am I missing something?

Oh, and many thanks for this awesome library, it really fills a niche.
I'll try to use it together with [fluent-jdbc](https://github.com/zsoltherpai/fluent-jdbc), that seems to use the same syntax for named parameters as the Spring JdbcTemplate.

**Comment by jodastephen** [comment]
Changing the type parameters of a method may be source compatible, but is not [binary compatible](https://wiki.eclipse.org/Evolving_Java-based_APIs_2).

In Java 8, the following compiles:

    Map<String, Object> params = Collections.singletonMap("key", "value");

In Java 7 I suspect you have to do this

    Map<String, Object> params = Collections.<String, Object>singletonMap("key", "value");

Given all this, I'm not sure its sensible to make a change to ElSql.

BTW we use [JDBI](http://jdbi.org/) now for the SQL side, but fluent-jdbc looks interesting too.

**Comment by zimmi** [comment]
I learned something new, thanks a lot for the information and the link!

In that case I agree that it's silly to break binary compatibility over this. Most of the time the parameters will be of mixed types, so we're back to Object anyway.

I'll close this issue then.

Have a nice weekend!
