### ISSUE TITLE
Nested loop support

### ISSUE THREAD

**Issue by evpaassen** [OpenGamma/ElSql#15]
Using loops in a nested way seems to be impossible, am I right? This could be very useful, however. For example when I have `x` columns which I want to match against `y` values.

Something like this: (This obviously won't work, because of the duplicate `@LOOPINDEX`).
```
@NAME(Find)
    SELECT
        id
    FROM
        tablename
    WHERE
        @LOOP(:numberOfSearchTerms)
            (
            @LOOP(:numberOfSearchFields)
               :searchField@LOOPINDEX @LIKE :searchTerm@LOOPINDEX)
               @LOOPJOIN OR
            )
            @LOOPJOIN AND
```

**Comment by evpaassen** [comment]
Thanks a lot for the quick solution! Just wondering, are there any plans to create a new release?

**Comment by jodastephen** [comment]
There is one open PR. If we get that in, a new release would make sense.
