### ISSUE TITLE
@PAGING tag does not allow literal values

### ISSUE THREAD

**Issue by evpaassen** [OpenGamma/ElSql#19]
The `@PAGING` tag currently does not allow literal values to be passed in. While this behaviour is correct according to the documentation (`@PAGING(offsetVariable,fetchVariable)`), allowing so could be useful in some cases.

For example when I always want to fetch the top `x` results, I'll have to add an hardcoded `offsetVariable = 0` param next to the variable `fetchVariable = x` param.

I could try to create a PR for this, if desired.

**Comment by jodastephen** [comment]
We do like PRs ;-)

**Comment by evpaassen** [comment]
OK, I'll give it a try in the next few days.
