### ISSUE TITLE
Escaping @ in SQL

### ISSUE THREAD

**Issue by andrewdmay** [OpenGamma/ElSql#28]
Perhaps I've missed it, but it would be useful to have a way to escape @ symbols that appear in the Query body and aren't ElSql tags. 
Looking at the parser it appears that any line starting with @ that isn't a recognized tag will throw an exception.

**Comment by jodastephen** [comment]
My testing suggests that this is only a problem if the @ symbol is the first non-whitespace character of the line. This seems like a reasonable constraint, unless you can show me an example where this causes trouble.
